spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgresDocker
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
